spring.application.name=sondhan-auth-service

app.org.name=Sondhan

jwt.private-key-path=classpath:keys/private.pem
jwt.public-key-path=classpath:keys/public.pem

#Mail Server
spring.mail.host=smtp.gmail.com
spring.mail.port=587
app.password=qrnx npiw faqf mztp
spring.mail.username=aunkurdas1111@gmail.com
spring.mail.password=${app.password}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

sondhan.email.from={spring.mail.username}


#Redis
#spring.data.redis.cluster.nodes=b-master-temp-redis:6380,a-slave-temp-redis:6379,c-slave-temp-redis:6381,c-master-temp-redis:6381,b-slave-temp-redis:6380,a-master-temp-redis:6379
